### PR TITLE
Adapte the ETL to TERRA-REF

### PR DESCRIPTION
**Pull request by bilalelhoudaigui**
Fixed sessions bug + minor modifications

### CODE REVIEW

**Comment by bilalelhoudaigui** [comment]
Thank you @dlebauer and @max-zilla for the modifications, the extraction is working without any issues, however there is a minor modification to add if it's possible.

In the [Search Study by StudyDbId](https://brapi.docs.apiary.io/#reference/study/search/get-search-studies-by-searchresultsdbid) call there is a documentationURL field which is used in our portal to link back to the data source.

Here is an example of a [call containing documentationURL](http://brapi.tropgenedb.cirad.fr:8888/rice/brapi/v1/studies/83) and a link to the study on [FAIDARE](https://urgi.versailles.inra.fr/faidare/?sources=http:%2F%2Ftropgenedb.cirad.fr&types=Phenotyping%20Study&page=1), the call correspond to the first result with _(CIRAD TropGENE data source link)_ referring to the [data source](http://tropgenedb.cirad.fr/tropgene/JSP/link.jsp?module=RICE&value=RESGEN&tref=study&cref=name&tabIndex=0&onglet=STUDIES&numero=0).

FAIDARE_CIRAD_datalink

In the case of TERRA REF this field is missing as a result, the URL is not shown next to the study name.

FAIDARE_TERRAREF_missing_datalink
<sup>_TERRA REF's screenshot was taken in dev environment_</sup>

Can you please add the _documentationURL_ field to studies as shown in the example above?

I hope that my explanation was clear otherwise please feel free to ask me for more details.

ping @cpommier

**Comment by dlebauer** [comment]
@bilalelhoudaigui sorry I missed this request. I've created an issue https://github.com/terraref/brapi/issues/36

Once this is implemented, will our data show up in the interface?

**Comment by cpommier** [comment]
@dlebauer I just saw that you have fixed this, thanks! We will add your data publicly next week.

**Comment by bilalelhoudaigui** [comment]
@dlebauer, No worries, Thank you for creating the issue.

Normally once the _documentationURL_ is added, the pipeline picks it up and adds it to the extracted data.

For the moment, the data can be shown even without _documentationURL_ (it can be added latter).

**Pull request merged**
